apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-paper
  namespace: minecraft
  labels:
    app: minecraft-paper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-paper
  template:
    metadata:
      labels:
        app: minecraft-paper
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21
        ports:
        - containerPort: 25565
          name: minecraft
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        - name: VERSION
          value: "LATEST"
        - name: MEMORY
          value: "2G"
        volumeMounts:
        - name: paper-data
          mountPath: /data
        resources:
          requests:
            cpu: 250m
            memory: 2Gi
          limits:
            cpu: "1"
            memory: 3Gi
      volumes:
      - name: paper-data
        persistentVolumeClaim:
          claimName: minecraft-paper-data
